import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface InvoiceLine {
  product: string;
  qty: number;
  price: number;
  total: number;
}

export interface InvoiceDoc {
  title: string;
  number: string;
  date: string;
  partyLabel: string;
  partyName: string;
  warehouse?: string;
  payment?: string;
  status?: string;
  lines: InvoiceLine[];
  subtotal: number;
  tax: number;
  discount: number;
  total: number;
  paid?: number;
  company?: { name?: string; address?: string; phone?: string; vat?: string };
  currency?: string;
}

export function generateInvoicePDF(doc: InvoiceDoc) {
  const pdf = new jsPDF({ unit: "mm", format: "a4" });
  const w = pdf.internal.pageSize.getWidth();
  const cur = doc.currency ?? "";
  const m = (n: number) => `${cur} ${Number(n).toFixed(2)}`;

  // Header
  pdf.setFontSize(20).setFont("helvetica", "bold");
  pdf.text(doc.company?.name ?? "Vortex ERP", 14, 18);
  pdf.setFontSize(9).setFont("helvetica", "normal").setTextColor(120);
  if (doc.company?.address) pdf.text(doc.company.address, 14, 24);
  if (doc.company?.phone) pdf.text(doc.company.phone, 14, 29);
  if (doc.company?.vat) pdf.text(`VAT: ${doc.company.vat}`, 14, 34);

  pdf.setFontSize(16).setFont("helvetica", "bold").setTextColor(0);
  pdf.text(doc.title, w - 14, 18, { align: "right" });
  pdf.setFontSize(10).setFont("helvetica", "normal").setTextColor(80);
  pdf.text(`#${doc.number}`, w - 14, 24, { align: "right" });
  pdf.text(doc.date, w - 14, 29, { align: "right" });

  // Party block
  pdf.setDrawColor(220).line(14, 42, w - 14, 42);
  pdf.setFontSize(9).setTextColor(120);
  pdf.text(doc.partyLabel.toUpperCase(), 14, 48);
  pdf.setFontSize(11).setTextColor(0).setFont("helvetica", "bold");
  pdf.text(doc.partyName, 14, 53);
  pdf.setFont("helvetica", "normal").setFontSize(9).setTextColor(80);
  if (doc.warehouse) pdf.text(`Warehouse: ${doc.warehouse}`, 14, 59);
  if (doc.payment) pdf.text(`Payment: ${doc.payment}`, w - 14, 53, { align: "right" });
  if (doc.status) pdf.text(`Status: ${doc.status}`, w - 14, 59, { align: "right" });

  // Items table
  autoTable(pdf, {
    startY: 66,
    head: [["#", "Product", "Qty", "Price", "Total"]],
    body: doc.lines.map((l, i) => [String(i + 1), l.product, String(l.qty), m(l.price), m(l.total)]),
    theme: "striped",
    headStyles: { fillColor: [30, 30, 35], textColor: 255, fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    columnStyles: { 0: { cellWidth: 12 }, 2: { halign: "right" }, 3: { halign: "right" }, 4: { halign: "right" } },
  });

  const endY = (pdf as any).lastAutoTable.finalY ?? 100;

  // Totals
  const tx = w - 14;
  const rows: [string, string][] = [
    ["Subtotal", m(doc.subtotal)],
    ["Tax", m(doc.tax)],
    ["Discount", m(doc.discount)],
    ["Total", m(doc.total)],
  ];
  if (doc.paid !== undefined) rows.push(["Paid", m(doc.paid)], ["Balance", m(doc.total - doc.paid)]);

  pdf.setFontSize(10);
  rows.forEach((r, i) => {
    const y = endY + 8 + i * 6;
    const bold = r[0] === "Total" || r[0] === "Balance";
    pdf.setFont("helvetica", bold ? "bold" : "normal");
    pdf.setTextColor(bold ? 0 : 90);
    pdf.text(r[0], tx - 50, y);
    pdf.text(r[1], tx, y, { align: "right" });
  });

  // Footer
  const fy = pdf.internal.pageSize.getHeight() - 12;
  pdf.setDrawColor(220).line(14, fy - 4, w - 14, fy - 4);
  pdf.setFontSize(8).setTextColor(140).setFont("helvetica", "normal");
  pdf.text("Thank you for your business — Generated by Vortex ERP", w / 2, fy, { align: "center" });

  pdf.save(`${doc.number}.pdf`);
}
